# 1. Имя нашего workflow
name: Run my tests

# 2. Триггеры: когда запускать
on:
  push:               # при пуше в указанные ветки
    branches: [ main, develop ]
  pull_request:       # при создании Pull Request'а в указанные ветки
    branches: [ main ]

# 3. Сами задачи
jobs:
  test:
    runs-on: ubuntu-latest   # на какой виртуальной ОС запускать (бесплатно)

    # 4. Шаги, которые нужно выполнить
    steps:
      # Шаг 1: Скачать код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Установить нужную версию Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Шаг 3: Установить зависимости из файла requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Шаг 4: Запустить тесты
      - name: Run tests with pytest
        run: |
          pytest


# name: Run autotests


#on: 
 # workflow_dispatch:
   # inputs:
   #   deployment_target:
    #    description: select tests to run
    #    required: true
    #    type: choice
    #    default: all
     #   options:
     #     - all

#jobs:
 # run-tests:
 #   runs-on: ubuntu-latest
 #   name: Tests
  #  steps:
  #    - name: Copy source code
  #      user: actions/checkout@v4
   #   - name: Set up Python env
   #     uses: actions/setup-python@v5
   #     with:
    #      python-version: "3.14"
    #  - name: install dependencies
     #   run: pip install -r requirements.txt
    #  - name: Run tests
    #    run: pytest -v
